databases:
  - name: macot_tinder
    databaseName: macot_tinder
    user: macot_tinder
    plan: free

services:
  - type: web
    name: macot_tinder
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: macot_tinder
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default